package de.egga.higher_order_java.schwartzian_transformation;

import java.util.HashMap;
import java.util.Map;

/**
 * @author egga
 */
public class SpaceTimeVehicle {

    private Map<String, Integer> ratings = new HashMap<>();

    public SpaceTimeVehicle() {
        ratings.put("The 456", 398);
        ratings.put("Alien", 856);
        ratings.put("Aaraanandal slime beast", 52);
        ratings.put("Abominable alien", -231);
        ratings.put("Aegis", 859);
        ratings.put("Aerolith", -542);
        ratings.put("Ageless", 352);
        ratings.put("Aldeberian", 645);
        ratings.put("Ameteli", 657);
        ratings.put("Ammonite", 964);
        ratings.put("Amorta", 391);
        ratings.put("Anchrola", 431);
        ratings.put("Andosian", 401);
        ratings.put("Anibusian", 942);
        ratings.put("Aquabi", 782);
        ratings.put("Aquarpey", 741);
        ratings.put("Arar Jecks", 107);
        ratings.put("Archies", -482);
        ratings.put("Arix (species)", 168);
        ratings.put("Arkonide", 422);
        ratings.put("Arucha", 139);
        ratings.put("Astracane leech", -862);
        ratings.put("Bactrian", -45);
        ratings.put("Balumin", -437);
        ratings.put("Bandersnatcher", -866);
        ratings.put("Bane (Dominion)", -754);
        ratings.put("Baracta", -131);
        ratings.put("Basprali", -318);
        ratings.put("Benelisan", 302);
        ratings.put("Berrus", -116);
        ratings.put("Berserker", -191);
        ratings.put("Blehurg", -949);
        ratings.put("Bobodix", 568);
        ratings.put("Bog wraith", -791);
        ratings.put("Borvali", -430);
        ratings.put("Breeble", -230);
        ratings.put("Bright Nobles", 567);
        ratings.put("Buukvirm", 284);
        ratings.put("Byndalk", 267);
        ratings.put("Caballan", 580);
        ratings.put("Callicon", -673);
        ratings.put("Canisian", 581);
        ratings.put("Ceccec", 570);
        ratings.put("Cerulian", -958);
        ratings.put("Chaktra", -852);
        ratings.put("Chantri Golem", 317);
        ratings.put("Charnal horde", 315);
        ratings.put("Charon (species)", -366);
        ratings.put("Chorodoron", -688);
        ratings.put("Chronomite", -463);
        ratings.put("Cimliss", -970);
        ratings.put("Cineraria", -752);
        ratings.put("Cirranin", -19);
        ratings.put("Citdbtbed", 50);
        ratings.put("Cnidarian", 695);
        ratings.put("Cobalite", 650);
        ratings.put("Collector", -647);
        ratings.put("Concepton", -776);
        ratings.put("Constructors of Destiny", 910);
        ratings.put("Council of Eight", -736);
        ratings.put("The Cran", -599);
        ratings.put("Craxon", -323);
        ratings.put("Cyberman", -86);
        ratings.put("Dahensa", 432);
        ratings.put("The Dark (Forever Dreaming)", 903);
        ratings.put("Dark Horde", -606);
        ratings.put("The Dark (Fear of the Dark)", 805);
        ratings.put("Daxzian", 758);
        ratings.put("Deathsmiths of Goth", -985);
        ratings.put("Deathworm Morphant", 720);
        ratings.put("Decevion", 916);
        ratings.put("Demon (Dalek War)", -755);
        ratings.put("Dentraal", -378);
        ratings.put("Devgherrian", -899);
        ratings.put("Dibinian", 885);
        ratings.put("Divergence", -160);
        ratings.put("Djinn", -926);
        ratings.put("Dox", 945);
        ratings.put("Dragon (Dragon Attack)", -648);
        ratings.put("Dramos (species)", 651);
        ratings.put("Drexxon", 386);
        ratings.put("Drolag", 905);
        ratings.put("Drudger", 81);
        ratings.put("Ectovore", -483);
        ratings.put("Edger", -876);
        ratings.put("Elemental Shade", 385);
        ratings.put("Elephine", -645);
        ratings.put("Ellillian", 660);
        ratings.put("Entropy Siren", 663);
        ratings.put("Erinancean", 633);
        ratings.put("Erosan", 291);
        ratings.put("Eskoni", 60);
        ratings.put("Esqueekeemmian", -46);
        ratings.put("Farrashian", -16);
        ratings.put("Feathered people", 286);
        ratings.put("Finliri", 957);
        ratings.put("Firbolg", 492);
        ratings.put("Fleshsmith", -790);
        ratings.put("Flower Cultures", -919);
        ratings.put("Fodoran", 632);
        ratings.put("Fostarone", 148);
        ratings.put("Freedonian", -773);
        ratings.put("Fuegolem", 222);
        ratings.put("Gaijin", 242);
        ratings.put("Galatean", -756);
        ratings.put("Gandagum", 224);
        ratings.put("Garaman", -550);
        ratings.put("Garvak", -996);
        ratings.put("Garvantine", -406);
        ratings.put("Gati", -624);
        ratings.put("Geathian", 145);
        ratings.put("Gell guard", -792);
        ratings.put("Gendhi", -61);
        ratings.put("Geomatide Macros", -799);
        ratings.put("Glarrock", -97);
        ratings.put("Glasseater", 956);
        ratings.put("Go-Ray", -580);
        ratings.put("Goronian", 527);
        ratings.put("Grelladian", 40);
        ratings.put("Grellig", -161);
        ratings.put("Grilon", 907);
        ratings.put("Grutcha", 540);
        ratings.put("Guermantian", 452);
        ratings.put("Guldreasi", -252);
        ratings.put("Gulfrarg", -512);
        ratings.put("Gumpii", -771);
        ratings.put("Haemogoth", 219);
        ratings.put("Halldon", -668);
        ratings.put("Hanakoi", 441);
        ratings.put("Harrowkind", 155);
        ratings.put("Haxalian", -690);
        ratings.put("Hedenexian", -515);
        ratings.put("Hedera", -291);
        ratings.put("Hellion", -551);
        ratings.put("H CONT.", -374);
        ratings.put("Hemvax Conflagration", -377);
        ratings.put("Histrix", -590);
        ratings.put("Hive of Mooj", -257);
        ratings.put("Huduct", 646);
        ratings.put("Hufko", -547);
        ratings.put("Hurgalnook", -946);
        ratings.put("Huskian", 746);
        ratings.put("Hussuloofian", -956);
        ratings.put("Hy-Bractor", -467);
        ratings.put("Hypnoredip", 857);
        ratings.put("Iarcho", -817);
        ratings.put("Ikoran", 585);
        ratings.put("Infinite warrior", -578);
        ratings.put("Iq-Qaba", -484);
        ratings.put("Isari", -22);
        ratings.put("Iska'lanz'rm", 606);
        ratings.put("Istervaalan", 543);
        ratings.put("Jagdagian", -295);
        ratings.put("Jalaphron", 733);
        ratings.put("Jariden", -530);
        ratings.put("Jathaa", -135);
        ratings.put("Jax", 699);
        ratings.put("Jell", 140);
        ratings.put("Jezark (species)", 202);
        ratings.put("Jomarian", 572);
        ratings.put("Joran", -785);
        ratings.put("Jullatii", 704);
        ratings.put("Julsaen", 887);
        ratings.put("Kagananaga Botizoid", 761);
        ratings.put("Kaldarean bedmite", 747);
        ratings.put("Kalekani", -532);
        ratings.put("Kapteynian", 968);
        ratings.put("Karkinian", -399);
        ratings.put("Kaveetch", 183);
        ratings.put("Ke Chedani", -497);
        ratings.put("Keltan", 430);
        ratings.put("Khameirian", -806);
        ratings.put("Kharitite", 569);
        ratings.put("Khorlthochloi", -235);
        ratings.put("Kladdavoreesh", 476);
        ratings.put("Kobold", -37);
        ratings.put("Kolranis", 912);
        ratings.put("Korjan anthropoid", 998);
        ratings.put("Kork", 544);
        ratings.put("Kosnax", -349);
        ratings.put("Koteem", -164);
        ratings.put("Krakenite", 469);
        ratings.put("Krampus", 742);
        ratings.put("Krayt", -729);
        ratings.put("Kredysonuzzi", 740);
        ratings.put("Krivani", -962);
        ratings.put("Kubthukian", 770);
        ratings.put("Kusk", -654);
        ratings.put("Kystra", -296);
        ratings.put("Lacaillan", -548);
        ratings.put("Laiderplacker", -864);
        ratings.put("Lamadine", -76);
        ratings.put("Lammasteen", 610);
        ratings.put("Lava snake", 494);
        ratings.put("Leppo", 498);
        ratings.put("Light-being", 625);
        ratings.put("Lightwanderer", 996);
        ratings.put("Lom", -242);
        ratings.put("Loomish", -714);
        ratings.put("Lords of Jelsen", 508);
        ratings.put("Loum", 206);
        ratings.put("Lucanian", -964);
        ratings.put("Lucentran", -203);
        ratings.put("Lurlak", -268);
        ratings.put("Luron", -508);
        ratings.put("Maakrian swamp-bear", 251);
        ratings.put("Maarcheen", -124);
        ratings.put("Malevilus", 37);
        ratings.put("Malkuthite", -460);
        ratings.put("Mammox", -912);
        ratings.put("Mandelbrot", -579);
        ratings.put("Mange Mites", -830);
        ratings.put("Martian (The Last Resort)", -633);
        ratings.put("Mede", 593);
        ratings.put("Medusoid", -162);
        ratings.put("Meep", 238);
        ratings.put("Megaluthian slimeskimmer", 200);
        ratings.put("Melkene", -402);
        ratings.put("Mirrorite", -55);
        ratings.put("Modrakanian", -412);
        ratings.put("Molag", -492);
        ratings.put("Monasticy of Slom", -700);
        ratings.put("Monopod", -930);
        ratings.put("Moog", -720);
        ratings.put("Morphuse", 670);
        ratings.put("Mutagenic protobioform", 436);
        ratings.put("Myloki", 216);
        ratings.put("N'Tian", 898);
        ratings.put("Narg (Tempest)", 417);
        ratings.put("Nethrass", -556);
        ratings.put("Never-were", 447);
        ratings.put("Nightmare Creature", -443);
        ratings.put("Null", 421);
        ratings.put("Oblongooni", -502);
        ratings.put("Okk", -258);
        ratings.put("Okrenian", 807);
        ratings.put("Omwanar League", 673);
        ratings.put("Onihr", 67);
        ratings.put("Ontraag", -925);
        ratings.put("Ooolatrii", 7);
        ratings.put("Oraapi", 450);
        ratings.put("Oroborous Worm", 554);
        ratings.put("Oshakarm", 493);
        ratings.put("P'Shem", -974);
        ratings.put("P'tarr", -455);
        ratings.put("Padrivole", 468);
        ratings.put("Pallushi", 950);
        ratings.put("Panic creature", -566);
        ratings.put("Pantachian Rock Skipper", 620);
        ratings.put("Paragrolli", -651);
        ratings.put("Pen-Shoza", -795);
        ratings.put("Perseus Corporeal", -665);
        ratings.put("Phoenix (species)", -742);
        ratings.put("Phoenix (The Bird of Fire)", -119);
        ratings.put("Pipe person", -683);
        ratings.put("Piscon", 146);
        ratings.put("Plath", -717);
        ratings.put("Plutonian microbe", -206);
        ratings.put("Polar Modrelian", -995);
        ratings.put("Posicarian", 594);
        ratings.put("Pranavore", 958);
        ratings.put("Propheetis", 331);
        ratings.put("Proximan", 631);
        ratings.put("Psionosphere", 161);
        ratings.put("Psionovore", -591);
        ratings.put("Pyron (species)", 424);
        ratings.put("Quagulan", -255);
        ratings.put("Quarsian", 131);
        ratings.put("Quevvil", 721);
        ratings.put("Q CONT.", 485);
        ratings.put("Quintani", -491);
        ratings.put("Quirkafleeg", -968);
        ratings.put("Rain (Pitter-Patter)", 737);
        ratings.put("Ralafean", 478);
        ratings.put("Ramossan", 971);
        ratings.put("Ranfo", 559);
        ratings.put("The Remote", -189);
        ratings.put("Ren'ai", -184);
        ratings.put("Reverent Pentiarchs of Loorn", -240);
        ratings.put("Rill", -5);
        ratings.put("Robo-destroyer", 929);
        ratings.put("Rock-eating Yellow-Belly", 123);
        ratings.put("Sabrewolf", -31);
        ratings.put("Saldisian", 783);
        ratings.put("The Sanctified", -498);
        ratings.put("Schirr", -553);
        ratings.put("Sclaponian", 556);
        ratings.put("Scorchie", 576);
        ratings.put("Selkie", -774);
        ratings.put("Semestran Interlude", -863);
        ratings.put("Semquess", -476);
        ratings.put("Sentient", -971);
        ratings.put("Sentient iron", 111);
        ratings.put("Serpentoidian", -417);
        ratings.put("Shad'ath", -302);
        ratings.put("Shadey", 531);
        ratings.put("Shamboni", 134);
        ratings.put("Shill", -325);
        ratings.put("Shinx", -781);
        ratings.put("Shlangiian", 904);
        ratings.put("Shovoran", -652);
        ratings.put("Shvone", 697);
        ratings.put("Silostophan", -927);
        ratings.put("Sittuun", 678);
        ratings.put("Six-legged camel", 28);
        ratings.put("Skishtari", -270);
        ratings.put("Sky-Sheep", -607);
        ratings.put("Slarvian", 519);
        ratings.put("Slime-frog", 516);
        ratings.put("Slimer", 530);
        ratings.put("Solarian (Prisoners of the Sun)", 558);
        ratings.put("Sorbazaran", 797);
        ratings.put("Space-Boar", 705);
        ratings.put("Spaceship Remote", 987);
        ratings.put("Spider germ", -41);
        ratings.put("Spindleking", -170);
        ratings.put("Sporax", -605);
        ratings.put("Spulver Worm", -952);
        ratings.put("Starman (species)", -179);
        ratings.put("Steigertrude", 487);
        ratings.put("Stingray", 930);
        ratings.put("Strigidae", 972);
        ratings.put("Super Krillitane", 798);
        ratings.put("Svillia", -514);
        ratings.put("Sycorax horse", 814);
        ratings.put("Tahnn", -363);
        ratings.put("Talerian", -289);
        ratings.put("Talichre", -180);
        ratings.put("Tandonian", -92);
        ratings.put("Tauride", -305);
        ratings.put("Tekazoid cave-beast", 845);
        ratings.put("Tendrak", -851);
        ratings.put("Terpsechian", -390);
        ratings.put("Terpsivore", 709);
        ratings.put("Teuthida", -138);
        ratings.put("The Ethereal", -401);
        ratings.put("Thetran", 928);
        ratings.put("Thieg", -304);
        ratings.put("Thraal", 607);
        ratings.put("Time Rider", -157);
        ratings.put("Torodon", 403);
        ratings.put("Tractite", -716);
        ratings.put("Traveller (Last Rites)", 255);
        ratings.put("Treasure hunting spider (A Tangled Web)", -219);
        ratings.put("Trichoate", -845);
        ratings.put("Trimestrain", -274);
        ratings.put("Tulokon", -631);
        ratings.put("Tyk", 781);
        ratings.put("Tymerian", -481);
        ratings.put("Tynaker", -265);
        ratings.put("Ug-Raptor", -423);
        ratings.put("Ulk-Ra", 466);
        ratings.put("Ulla", 954);
        ratings.put("The Unnoticed", -894);
        ratings.put("Urglanic Shapeshifters", -708);
        ratings.put("Urodelian", -99);
        ratings.put("Ursulan", -332);
        ratings.put("Uthian", 130);
        ratings.put("Valkari", 793);
        ratings.put("Vandrogon", 991);
        ratings.put("Vardon", 590);
        ratings.put("Vashta Nerada", -506);
        ratings.put("Veltino", -213);
        ratings.put("Vendraxoo", -623);
        ratings.put("Ventrosian", 388);
        ratings.put("Verron", -38);
        ratings.put("Vilp", 872);
        ratings.put("Virtor", -505);
        ratings.put("Viskili", -682);
        ratings.put("Volnexian", -813);
        ratings.put("Voltranon", -639);
        ratings.put("Vorcasian Hordes", 920);
        ratings.put("Vorkazian", 160);
        ratings.put("Vorpon", -106);
        ratings.put("Vox (The Poison Planet)", 665);
        ratings.put("Vykoid", -69);
        ratings.put("Wallarian", -924);
        ratings.put("Walrus-human hybrid", 934);
        ratings.put("Warfreek", 54);
        ratings.put("Waska", -973);
        ratings.put("Weave", 30);
        ratings.put("Wyzyna", -745);
        ratings.put("Xanthoid", -120);
        ratings.put("Xarantharax", -397);
        ratings.put("Xxxxxxxxxlanthi", -489);
        ratings.put("Xylok", -513);
        ratings.put("Xyz", -571);
        ratings.put("Yemayan", 641);
        ratings.put("Yesodite", -216);
        ratings.put("Yevron", -698);
        ratings.put("Ymerl", -602);
        ratings.put("Yogloth", -6);
        ratings.put("Zantoran", -906);
        ratings.put("Zargreg", 106);
        ratings.put("Zhurunti", -44);
        ratings.put("Zithra", 428);
        ratings.put("Zodin", 410);
        ratings.put("Zu'nar", -778);
        ratings.put("Zynog", -595);

    }

    public Integer visitPlanetAndAskForHelp(String name) {
        return ratings.get(name);
    }

}
